kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    listenAddress: "0.0.0.0"
  - containerPort: 6817
    hostPort: 6817
    listenAddress: "0.0.0.0"
  - containerPort: 6818
    hostPort: 6818
    listenAddress: "0.0.0.0"
  - containerPort: 6819
    hostPort: 6819
    listenAddress: "0.0.0.0"
- role: worker
- role: worker

