# BeeGFS Storage Service Role - Handlers

- name: Restart BeeGFS storage service
  ansible.builtin.systemd:
    name: beegfs-storage
    state: restarted
    daemon_reload: true
  when: not install_only
