apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops

resources:
  - namespace.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - bucket-job.yaml

commonLabels:
  app.kubernetes.io/name: minio
  app.kubernetes.io/component: object-storage
  app.kubernetes.io/part-of: mlops-stack

images:
  - name: quay.io/minio/minio
    newTag: RELEASE.2024-10-02T17-50-41Z
