apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops

resources:
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: mlflow
  app.kubernetes.io/component: tracking-server
  app.kubernetes.io/part-of: mlops-stack

images:
  - name: ghcr.io/mlflow/mlflow
    newTag: v2.9.2
