apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops

resources:
  - secret.yaml
  - configmap.yaml
  - pvc.yaml
  - statefulset.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: postgresql
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: mlops-stack

images:
  - name: postgres
    newTag: "15.4"
