# BeeGFS Management Service Role - Handlers

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart BeeGFS management service
  ansible.builtin.systemd:
    name: beegfs-mgmtd
    state: restarted
    daemon_reload: true
  when: not install_only
